control_gains: {p: 4.0, d: 1.0}
# Controls for search pattern sequence
land_time: 20.0
start_time: 5.0
inter_pose_delay: 3.0
offboard: 0   # Is drone currently in offboard mode or not
# Position setpoints relative to where offboard mode is enabled
x_rel_setpoint: 0.0
y_rel_setpoint: 0.0
z_rel_setpoint: 0.0
theta_rel_setpoint: 0.0 # NOT yet implemented
# Values that force negative Z or zero velocity
tag_detect: 0
land_now: 0
zero_vel: 0

