control_gains: {p: 4.0, d: 1.0, p_yaw: 4.0, d_yaw: 1.0}
# Controls for search pattern sequence
land_time: 20.0
start_time: 5.0
inter_pose_delay: 3.0
offboard: 0   # Is drone currently in offboard mode or not
# Position setpoints relative to where offboard mode is enabled
# X Y Z is RIGHT FORWARDS UP
x_rel_setpoint: 0.0
y_rel_setpoint: 0.0
z_rel_setpoint: 0.0
yaw_rel_setpoint: 0.0 # NOT yet implemented
# Flags for april tag detection and pose
tag_detect: 0
# X Y Z is RIGHT FORWARDS UP
filtered_tag_x: 0.0
filtered_tag_y: 0.0
# Values that force negative Z or zero velocity
land_now: 0
zero_vel: 0
# April-tag Filtering related
ransac_inlier_threshold: 0.1
pose_filter_min_points: 10 # Originally 10
pose_filter_covariance_threshold: 0.4  # Orig. 0.3: Must be less than or equal